import "./globals.css";

export const metadata = {
  title: "Full Stack Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="w-screen md:w-4/5 xl:w-3/4 mx-auto h-screen">{children}</body>
    </html>
  );
}
